name: Stop Uploaders
description: Use testnet-deploy to stop the uploaders for the environment
inputs:
  network-name:
    description: The name of the network
    required: true

runs:
  using: composite
  steps:
    - name: stop uploaders
      env:
        NETWORK_NAME: ${{ inputs.network-name }}
      shell: bash
      run: |
        set -e

        cd sn-testnet-deploy
        testnet-deploy clients stop-uploaders --name $NETWORK_NAME
